services:
  redis_rdb:
    image: redis:latest
    container_name: redis_rdb
    command: ["redis-server", "--save", "60", "1"]
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis_rdb:/data

  redis_aof:
    image: redis:latest
    container_name: redis_aof
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6380:6379"
    volumes:
      - ./data/redis_aof:/data

  beanstalkd:
    image: schickling/beanstalkd
    container_name: beanstalkd
    ports:
      - "11300:11300"
